# the author information
author:
  # author name
  name: unsigned-long2
  # author E-Mail
  eMail: 3079625093@qq.com
  # author address
  address: WuHan China

# the threshold for algorithm or values
threshold:
  # the threshold to judge whether two doubles are equal
  DOUBLE_EQ: 1E-15
  # the coordinate transformation accuracy threshold
  POSITION: 1E-8
  # the threshold for iterate algorithm
  ITERATE: 1E-12

# the origin for the specific global position systems
# attention! the origins are expressed in the form of modify julian day
timeSystem:
  GPSTOrigin:
    year: 1980
    month: 1
    day: 6
    hour: 0
    minute: 0
    second: 0
  BDTOrigin:
    year: 2006
    month: 1
    day: 1
    hour: 0
    minute: 0
    second: 0

# the reference ellipsoids
RefEllipsoid:
  WGS1984:
    # semi major axis of the ellipsoid
    a: 6378137.0
    # inverse flattening
    fInv: 298.257223563
  CGCS2000:
    # semi major axis of the ellipsoid
    a: 6378137.0
    # inverse flattening
    fInv: 298.257222101